try:
    raise Exception('HiThere')
except :
    print('发生异常 !')
    